Fix LRU cache bug with Ray
For some reason, the ray actors were failing to properly import
the cython code in the lru-dict library. Kept giving the error
`AttributeError: type object 'LRU' has no attribute '__len__'`

Switching to pylru (pure python) fixed the issues